### ISSUE TITLE
aspect ratio 2:1

### ISSUE THREAD

**Issue by ftoledo** [ultramango/gear360pano#14]
I read in the facebook doc (for 360 photo upload) that the file must have 2:1 aspect ratio

i test the script and the original file are 7776x3888 but the stitched are 7776x2246

This issue sems to cause to facebook do not detect as panorama photo

**Comment by ultramango** [comment]
This is a bit weird, and I can't reproduce the problem (just tested this under Windows). Could you send me the file that cases this? Also ensure if the source panorama file is indeed 7776x3888.

**Comment by ftoledo** [comment]
Hi!
i use it on linux (Debian stretch)
hugin version 2016.2.0~rc2+dfsg-2+b1

<pre>
ragnarok@ragnarok:~/360$ file 360_0016.JPG 
360_0016.JPG: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=11, description=SAMSUNG    , manufacturer=SAMSUNG, model=SM-C200, orientation=upper-left, xresolution=208, yresolution=216, resolutionunit=2, software=0.76, datetime=2017:01:02 21:50:30], baseline, precision 8, 7776x3888, frames 3

ragnarok@ragnarok:~/360$ ./gear360pano/gear360pano.cmd 360_0016.JPG 
Processing input images (nona)
Stitching input images (enblend)
enblend: info: loading next image: /tmp/tmp.vbUZs34i14/out0000.tif 1/1
enblend: info: loading next image: /tmp/tmp.vbUZs34i14/out0001.tif 1/1
enblend: info: writing final output
enblend: warning: must fall back to export image without alpha channel
Panorama written to ./360_0016_pano.jpg, took: 24 s

ragnarok@ragnarok:~/360$ file 360_0016_pano.jpg 
360_0016_pano.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 7776x2246, frames 3

</pre>

http://bbs.docsud.com.ar/tmp/360/360_0016.JPG
http://bbs.docsud.com.ar/tmp/360/360_0016_pano.jpg

**Comment by ultramango** [comment]
Thanks for the images (you can remove them from the server if you want). On my current machine (Windows 10 x64, Hugin 2016.2.0.be8da0221960 built by Thomas) panorama generates fine and the image size is correct... Your stitched photo compared to mine is cropped (not resized/stretched).

Please inspect your `gear360tmpl.pto` file, somewhere at the beginning there should be this line:
`p f2 w7776 h3888 v360  E8.32193 R0 n"TIFF_m c:LZW r:CROP"` ensure that it says `3888` and not `2246`, or you can just redownload file from here.

Note: for the moment I'd exclude some weird bugs in Hugin or other libraries.

**Comment by ftoledo** [comment]
i have a outdate template. I pull and solve the issue! 
thanks!
