### ISSUE TITLE
Problem uploading to Google photo

### ISSUE THREAD

**Issue by Ry0** [ultramango/gear360pano#15]
Thank you for very nice scripts.
I want to connect Gear 360 to my PC directly and upload the picture to Google photo without using Gear 360 Manager.
For the reason, I found this repository.
I have an question.

After creating equirectangular panorama with the following command, I uploaded it to Google photo.
But the picture is not recognized as 360° photography.

```bash
gear360pano.cmd 360_0001.JPG
```

I know that there is not a problem with your script.
Could you tell me if you have some information about this problem?
Thank you in advance.

**Comment by ftoledo** [comment]
This script put metadata in the stitched output file, maybe for google need more exifs fields?
Can you provide some url on google photo that show as 360 photo ?

**Comment by ftoledo** [comment]
Also, can you test if facebook get you photo as 360?

**Comment by Ry0** [comment]
@ftoledo thank you for reply.

I compared the exifs of successful and failing images.

![screenshot from 2017-03-14 04 53 12](https://cloud.githubusercontent.com/assets/8924325/23872993/d05fca6e-0873-11e7-99e6-1e360e06be83.png)
(Left: the image file created by Gear Manager
 Right: the image generated by `gear360pano.cmd`)

As a result of try and error, I found that tags shown below are important for google photo.

```bash
Use Panorama Viewer             : True
Cropped Area Image Width Pixels : 7776
Cropped Area Image Height Pixels: 3888
Full Pano Width Pixels          : 7776
Full Pano Height Pixels         : 3888
Cropped Area Left Pixels        : 0
Cropped Area Top Pixels         : 0
Pose Heading Degrees            : 0.000000
Pose Pitch Degrees              : 0.000000
Pose Roll Degrees               : 0.000000
Initial View Heading Degrees    : 0
Initial View Pitch Degrees      : 0
Initial View Roll Degrees       : 0
```

So, I changed the script like this.
[gear360pano.cmd#L105](https://github.com/ultramango/gear360pano/blob/master/gear360pano.cmd#L105)

```diff
+ # get the image size
+ IMG_WIDTH=`identify -format "%w" $1`
+ IMG_HEIGHT=`identify -format "%h" $1`

run_command "exiftool" "-ProjectionType=equirectangular" \
            "-q" \
            "-m" \
            "-TagsFromFile" "$1" \
            "-exif:all" \
            "--FocalLength" \
            "--FieldOfView" \
            "--ThumbnailImage" \
            "--PreviewImage" \
            "--EncodingProcess" \
            "--YCbCrSubSampling" \
            "--Compression" \
+             "-UsePanoramaViewer=True" \
+             "-CroppedAreaImageWidthPixels=$IMG_WIDTH" \
+             "-CroppedAreaImageHeightPixels=$IMG_HEIGHT" \
+             "-FullPanoWidthPixels=$IMG_WIDTH" \
+             "-FullPanoHeightPixels=$IMG_HEIGHT" \
+             "-CroppedAreaLeftPixels=0" \
+             "-CroppedAreaTopPixels=0" \
+             "-PoseHeadingDegrees=0.000000" \
+             "-PosePitchDegrees=0.000000" \
+             "-PoseRollDegrees=0.000000" \
+             "-InitialViewHeadingDegrees=0" \
+             "-InitialViewPitchDegrees=0" \
+             "-InitialViewRollDegrees=0" \
            "$OUTNAME"
```

As a result, the photo was recognized well on both Google photo and facebook.

### Google photo
![google_photo](https://cloud.githubusercontent.com/assets/8924325/23873473/7ffed0cc-0875-11e7-91b2-bb7d83990bd0.png)

### facebook
![screenshot from 2017-03-14 05 03 59](https://cloud.githubusercontent.com/assets/8924325/23873528/b5deadac-0875-11e7-9908-48649e6a1f55.png)

Thank you for giving important info！！

**Comment by ftoledo** [comment]
cool! i hope that @ultramango wil merge this patch!

Saludos!

**Comment by ultramango** [comment]
Thanks for ready to use fix! I just integrated it.

I decided to go with static values for the image size:

1. Anyway the image size is embedded into the panorama template.
2. It adds extra dependency (weak, as most of the systems usually have ImageMagick).
