### ISSUE TITLE
How to create an initial template using Hugin

### ISSUE THREAD

**Issue by Ry0** [ultramango/gear360pano#16]
I am creating own template using Hugin, because generated picture was misaligned when using the template uploaded on Github.
I created it by watching the tutorial video uploaded to Youtube, but I do not know how to create control points.

There was no change when creating control points and not creating.

![resized](https://cloud.githubusercontent.com/assets/8924325/24083131/e394d192-0d14-11e7-8b0f-26b27420986a.jpg)

I read the note written in the description section of Youtube.
Is the version of Hugin I use bad? (The version is 2013.0.0.4692917e7a55.)
If there is no problem, would you like to upload the file including 360_0529.JPG described in the template(`gear360tmpl.pto`)?
Accordingly, I want to confirm this problem.

Also, how accurate is the image created by Hugin stitched?
I am glad if you show me the example of the result.

I appreciate your help.
Thank you.

**Comment by ultramango** [comment]
Hi,

Do you have any previous experience stitching panoramas using Hugin?

The workflow is like this:

1. Add photos, set masks, etc. (just like in the photo).
2. Add control points (same points on two different photos).
3. Optimise panorama parameters.
4. Once satisfied stitch panorama.

Point 3 is tricky as at this step Hugin actually modifies parameters of photos (their position, distortion, etc.) to match them together. When I was creating the template I used, more or less, trial and error which parameters should be optimised.

L.

**Comment by Ry0** [comment]
@ultramango Sorry for the late reply. 
It is the first time I have used hugin.
It seems that the modification of the parameter was insufficient.
So, I will study from basically usage of Hugin.
Thanks for your advice.

**Comment by ultramango** [comment]
No worries.

The key is the optimisation process which will modify the photos parameters (rotation, movement, etc.) to fit them all together.

Also ensure that you have control points that point to the same things on various photos.

L.
