### ISSUE TITLE
Script is not working with Ubuntu 16.04

### ISSUE THREAD

**Issue by vincenttschanz** [ultramango/gear360pano#2]
Hugin and imagemagick installed.
I dropped a jpg from the Gear VR in the gear360pano folder and launched the script : 
  
`./gear360pano.sh 360_0001.JPG 
./gear360pano.sh: 19: ./gear360pano.sh: function: not found
./gear360pano.sh: 23: ./gear360pano.sh: Syntax error: "}" unexpected
`

Let me know if I can provide additional informations

btw, thanks a lot for your script!

**Comment by ultramango** [comment]
Hi there!

As a quick fix try to change the first line ([shebang](https://en.wikipedia.org/wiki/Shebang_(Unix))) to `#!/bin/bash`.

I'm not good at writing shell scripts and especially them to be highly portable between different shells. By default I use `sh` and usually fell into a trap that on most systems it's a link to `bash`, in case of Ubuntu it must be a simple shell that does not accept functions.

Out of laziness I'll just make the `bash` explicit.

**Comment by vincenttschanz** [comment]
Great! It's working now, thanks!
