### ISSUE TITLE
Support for 2017 version

### ISSUE THREAD

**Issue by sfrique** [ultramango/gear360pano#20]
It would be nice if it had support for also 2017 version.

**Comment by ultramango** [comment]
Hi,

I'll see what I can do. Do you have a source of some samples or have some that I could use as a reference? I could, quickly, only find one poor unstitched photo.

L.

**Comment by sfrique** [comment]
Yes i can get some samples and send to you.

How should i send it?
I just got it.

**Comment by ultramango** [comment]
Hmm... Upload password protected zip using one of the online services, e.g.:

https://uploadfiles.io/

Then send me the link and password to: gear360_2017@l.bit987.com .

If you have problems then we can try a different method.

If it's not a trouble, when taking sample photos choose environment which has a lot of details in around, it helps creating template file.

L.

**Comment by sfrique** [comment]
I am going to take a few more pictures now, and then send them to you.

**Comment by sfrique** [comment]
Sorry fo the delay, just sent you the data.

**Comment by ultramango** [comment]
Got it, thanks.

**Comment by ultramango** [comment]
I added preliminary support for gen2 version. As time allows I will try to improve the template (I think it's not as good as for gen1).
