### ISSUE TITLE
Image stitching in ubuntu server

### ISSUE THREAD

**Issue by juniorwebunitygames** [ultramango/gear360pano#21]
getting following issue after running for i in 360*.JPG; do ./gear360pano.cmd $i; done command from command prompt.
![2017-06-07_130937](https://user-images.githubusercontent.com/29247688/26867394-cbc25cfe-4b82-11e7-8f16-1c9b3ac6d611.jpg)

**Comment by ultramango** [comment]
I suspect you might have not enough free memory, how much does the machine have?

    free -h

See also this:

    dmesg | grep oom

to see if out-of-memory condition has been called.

**Comment by juniorwebunitygames** [comment]
Using free -h
i got
total mem : 990M
used mem : 454M
free mem : 437M
shared mem : 21M
buff/cache mem : 98M
available mem : 473M

So it is sufficient for stitching images ?

**Comment by ultramango** [comment]
Can't find any official Hugin requirements, but 1 GB of memory might not be enough to stitch such a big panorama.

You can edit the script and add these options (I'm guessing here a lot): ```--no-optimize -m 400``` to ```enblend``` command, but:

- it might take long time for panorama stitching,
- it might freeze your machine to the point you have to reboot it.

L.
