### ISSUE TITLE
Add support for geotagging from GPX

### ISSUE THREAD

**Issue by neuhaus** [ultramango/gear360pano#22]
Hi,

here's a feature request. There is some software that does this but perhaps you are inclined to merge it into your project:

Add GPS location to EXIF data from a separate GPX file.

With this new feature your script would be a good solution for batch processing of pictures taken prior to uploading them to Mapillary.

**Comment by neuhaus** [comment]
I think it's somewhat out of the scope of this script 😄 
A good solution would have to interpolate GPS data in between two data points, not easy to do in a CMD or bash script...

**Comment by ultramango** [comment]
Hi,

I agree that's a bit beyond the scope of this script :) .

There are a lot of existing software for doing this: darktable, digikam (not sure), qgis, gpsbabel (not sure).

And doing this in scripting would be a nightmare, especially for Windows (I'm already stretching the limits here).

**Comment by neuhaus** [comment]
Since I happened to have booted Windows, I used [GeoSetter](http://www.geosetter.de/).
