### ISSUE TITLE
Ignore images that have already been processed

### ISSUE THREAD

**Issue by neuhaus** [ultramango/gear360pano#25]
Feature request:

Please add an option to skip over existing stitched pictures.

**Comment by ftoledo** [comment]
how to use this script? 
i never get a stiched image 

mkdir out
for A in `ls 360*.JPG` ; do gear360pano.cmd $A out/$A; done

**Comment by ultramango** [comment]
There's an updated doc, do this:

    gear360pano.cmd 360*.JPG

Your files will be in ```html/data```, you can set the output directory using ```o``` parameter, ex. ```-o out```.

BTW: it's enough to do:

    for A in 360*.JPG; do echo "hello"; done

```ls``` is redundant (actually it creates an extra process).

**Comment by ultramango** [comment]
Processed files are skipped if they exist in target directory.
