### ISSUE TITLE
Script will not work when run from a different path

### ISSUE THREAD

**Issue by ultramango** [ultramango/gear360pano#3]
Script will not work when run from a different path because it will not find `pto` template file.

Solution: there's a way of detecting location of the script and the template file should be taken from there (the answer is somewhere on stackoverflow).

**Comment by lethalrush** [comment]
Hi, I've installed cygwin, Hugin, and downloaded gear360pano.  When I try to run it with a Gear360 photo as input, I get:

Processing input images (nona)
WARN: (d:/works/hugin-2016.0.0/src/hugin_base/panodata/Panorama.cpp:2070) readData(): Failed to read from dataInput.  
error while parsing panos tool script: gear360tmpl.pto
Error while running nona

1) The warning has a path at d:, but I do not have a d: drive
2) The photos are in the same directory as gear360pano
3) If I need to move the gear360pano directory somewhere before using, please let me know where.

**Comment by ultramango** [comment]
Hi,

Check these:

1. File ```gear360tmpl.pto``` is in the same directory as script.
2. Be sure that the current directory is the same as script's directory (you have to be inside the same directory as the script).

Let me know if it helped.

"d:/" path might be misleading, it just points to source code where from the binary was comiled.

I will remove cygwin dependency soon (it's an overkill for such simple script).

**Comment by ultramango** [comment]
Latest version should support executing script from other paths.
