### ISSUE TITLE
Hugin window opens and makes computer unusable 

### ISSUE THREAD

**Issue by miltonlaufer** [ultramango/gear360pano#34]
Hi! First of all, thank you so much: this script is great. It even stitches the panorama better than the one that comes with the camera!

I have a problem running the video script (though this happens also with the panorama script, but in that case doesn't bother): when the panorama scripts (which is called by the video script for each frame) runs Hugin, that opens for a second a window. The problem is this turns impossible to use the computer, because that window gets the focus and I can't do anything on other windows.

Is there any workaround for this?

Edit: this happens using Ubuntu 16.04, with the Hugin from the official repo.

Thank you so much!

**Comment by evertvorster** [comment]
Hi there, Milton. 

It is strange that the script opens any window, it does not do that on my computer. (Arch linux)
Can you post a little of your console output?

The reason I ask is that hugin is not actually used by the script, only some of the panotools that Hugin also relies upon. 

-Evert-

**Comment by evertvorster** [comment]
I'm stumped. 
Thanks for the thorough reply, and the small video.

One thing you could try is to run each of the commands in the script one by one on the terminal to see which one it is that is creating that popup. 

I am having a guess that .pto is defined as a Hugin file somewhere in your system setup, and it tries to open Hugin every time the system reads a .pto file. However, this should not happen from the command line.

**Comment by miltonlaufer** [comment]
I think that you're right.The PTO file type is associated with Hugin. What I don't understand is why, after editing every place where that association appears, is still opening the window! Anyway, it seems more a problem of my computer than of your script. 
Thank you again!
