### ISSUE TITLE
Script adds extra frames to my video

### ISSUE THREAD

**Issue by evertvorster** [ultramango/gear360pano#35]
The ffmpeg command that stitches the video from frames is causing extra frames to be inserted into the output video when compared to the input video. 

In my case I have a test video, 449 frames long. After processing, it was 539 frames long. 

The root cause of this is that ffmpeg assumes the input framerate to be 25, and the script sets the output framerate to 30. 

The quick and easy fix is to put the -r 30 before the -i in that command. This then tells ffmpeg that the input framerate is 30, and it will preserve that unless told otherwise.

Kind regards,
-Evert-

**Comment by ultramango** [comment]
Now framerate should be kept from the source video. Extra frames could have came from the fact that the real fps is 29.97 and not 30.00. I'm closing the issue, but let me know if there's still problem with that.
