### ISSUE TITLE
improve image quality of extracted frames

### ISSUE THREAD

**Issue by evertvorster** [ultramango/gear360pano#36]
Hi there. 
Ffmpeg uses standard compression for the extracted .jpg files from the video. Since we will be doing transforms on it, it is better to use a highest quality possible. 
Please consider changing 
run_command ffmpeg -y -i "$1" "$FRAMESTEMPDIR/$IMAGETMPL"
to
run_command ffmpeg -y -i "$1" -q:v 2 "$FRAMESTEMPDIR/$IMAGETMPL"

Kind regards,
Evert

**Comment by ultramango** [comment]
Hi!

Thanks for the tip. Will do in next pack of improvements (I'm thinking about having options for speed and quality).

Note 1 to self: ```-q:v N``` is alias for ```-qscale:v N```, when N lower the quality goes up.
Note 2 to self: speed: 148 s (current) vs 154 s (with N = 2), 131 frames video.

**Comment by ultramango** [comment]
Included in latest release (again - please verify, many change and I might have omitted something).
