### ISSUE TITLE
improve quality of final output

### ISSUE THREAD

**Issue by evertvorster** [ultramango/gear360pano#37]
Hi there. 
Since this script is getting so good on quality, it's a shame to throw it away at the end. 
I use the following as my output command:
run_command ffmpeg -y -f image2 -r 30 -i "$OUTTEMPDIR/$IMAGETMPLENC" -r 30 -s 3840:1920 -c:v libx265 -x265-params crf=18  "$OUTTEMPDIR$

From here I do more video editing on Blender/Kdenlive, so I want the maximum quality. Some others might want lower bitrates, but even at crf=26 (default for x264) the x265 encoding has twice the quality of x264

-Evert-

**Comment by ultramango** [comment]
Hello,

Is there a big time penalty when using x265? I remember it being quite slow (at the benefit of better quality).

Thanks.
L.

**Comment by evertvorster** [comment]
There is a bit of a time penalty. However, considering the time scales already involved here it does not make THAT big of a difference.

**Comment by ultramango** [comment]
I've improved default quality as suggested. There's also ```--speed```. Re-open if the output is still low-quality :) .

**Comment by akrinke** [comment]
However, x265 has the disadvantage of not beeing supported by Firefox and Chrome. Therefore, the generated HTML page did not work for me at first. It took a moment to realize the codec is the problem. Everything works fine with x264.

**Comment by ultramango** [comment]
Hmm... good point; I'll reconsider making x264 default and having x265 as an option.
