### ISSUE TITLE
Time Lapse video does not encode

### ISSUE THREAD

**Issue by evertvorster** [ultramango/gear360pano#38]
Hi there. 
When using the Gear 360 in time lapse mode, the video does not have an audio component. 
When running gear360video.cmd on it, the video encodes the frames properly, and stitches them in a video. However, when trying to extract the audio from the original (which does not have an audio stream) the script produces this error:

Output #0, adts, to './tmp.0twQCgYXU3/tmpaudio.aac':
Output file #0 does not contain any stream
Error while running ffmpeg
Removing temporary directories...

It then very helpfully removes the properly encoded output video. 
It should be possible to detect whether a video has an audio stream, and just skip this step if there is no audio to be encoded.

-Evert-

**Comment by ultramango** [comment]
Should be fixed now, let me know if the problem still exists.
