### ISSUE TITLE
Preliminary support for 2560x1280 video

### ISSUE THREAD

**Issue by durkie** [ultramango/gear360pano#39]
I've got some preliminary control points here that seem to stitch together pretty well. These were all done by hand using my own images, so I'm not sure if there is a more rigorous way of coming up with them or not.
```
c n0 N1 x118 y302 X2404 Y318 t0
c n0 N1 x1260.50736957882 y718.499647294616 X1326 Y722 t0
c n0 N1 x100 y477.333333333333 X2533 Y452 t0
c n0 N1 x117.854893798074 y330.293872950354 X2430 Y321 t0
c n0 N1 x14 y473 X2465 Y494 t0
c n0 N1 x893 y1179 X1637 Y1220 t0
c n0 N1 x1189 y406 X1350 Y408 t0
c n0 N1 x30.4484529469869 y575.91995423234 X2520 Y607 t0
c n0 N1 x1039.00000915503 y146.000010896103 X1574 Y206 t0
c n0 N1 x67 y887 X2469 Y884 t0
c n0 N1 x39 y406 X2443 Y435 t0
c n0 N1 x35 y752 X2504 Y752 t0
c n0 N1 x269 y126 X2253 Y161 t0
c n0 N1 x872 y124 X1642 Y62 t0
```

**Comment by ultramango** [comment]
Hi,

Could you send a full pto file? The important bits are actually few first lines which contain how to transform images.

Control points are used to actually create numbers that tell Hugin (actually ```nona```) how to transform images from circular fisheye to equirectangular panorama.

Thanks,
L.

**Comment by durkie** [comment]
sure -- i put it here: https://gist.github.com/durkie/7a02be64b05a4efaf4f834b70254e507

**Comment by ultramango** [comment]
I've added 2k video support to the latest release/push. Let me know if it doesn't work (by principle it should).
