### ISSUE TITLE
Detailed manual?

### ISSUE THREAD

**Issue by Gutje** [ultramango/gear360pano#4]
As a newby to cygwin and hugin i would love to see a detailed manual on how to run this script.

Ive tried to start it from cygwin terminal but than get an error on line 5.

$ gear360pano.sh 360_150.JPG
/usr/bin/gear360pano.sh: regel 5: syntaxfout nabij onverwacht symbool 'newline'
/usr/bin/gear360pano.sh: regel 5: `<!DOCTYPE html>'

So i would like to learn where exactly put the .sh and .pto files and how to run it/them.

**Comment by ultramango** [comment]
Hi.

Thanks for your feedback. First version of the script is/was intended for more experienced users.

Next time if you paste any messages please provide them in English, you can do that by running the script like that: ```LC_ALL="C" ./script_to_run```. Also writing which system or version you are using would be helpful.

I'll check what the problem might be and if I can fix it.

**Comment by ultramango** [comment]
Please try newest version that should work without cygwin. ```.pto``` file should be in the same directory as the script itself.
