### ISSUE TITLE
compiling multiblend

### ISSUE THREAD

**Issue by impca** [ultramango/gear360pano#41]
I followed the installation guide, but was unable to compile multiblend using the g++ invocation example given in the readme. Anyways, I eventually managed to do it. If anybody encounters similar problems and the compilation fails, try reordeing the g++ parameters like this and it should succeed:

g++ -msse2 -O3 multiblend.cpp -o multiblend -ltiff -ltiffxx -ljpeg -lpng

**Comment by ultramango** [comment]
Hi,

Interesting... which version of ```g++``` are you using (```g++ --version```)? "Standard" Linux or MacOS or some other unix flavour? What error messages (missing libraries?)?

For my Arch Linux ```g++``` 7.2.0 both versions (ordering) of ```g++``` command work.

Anyway I put the alternative command in README.md.

Cheers,
L.

**Comment by impca** [comment]
Oh, that explains a lot. This is an older Ubuntu machine and thus an older compiler version.

g++ (Ubuntu 4.9.1-16ubuntu6) 4.9.1

**Comment by ultramango** [comment]
Ancient :) . I'm closing the case then but I'll leave the help in main README file.
