### ISSUE TITLE
Batch Video Stitching 

### ISSUE THREAD

**Issue by cesifoti** [ultramango/gear360pano#7]
Hi,
I am doing VR filmmaking with a Samsung gear 360 and sometimes produce 100s of MP4s in a day. I am looking for a command line solution that would allow me to batch stitch videos to a directory overnight. Something like:

Videostitcher.cmd c:/source_directory c:/target_directory. 

Can your code do this? And if it doesn't, are u considering adding that feature?

**Comment by ultramango** [comment]
Hi,

I've been doing some experiments before already (I hate the bundled video editor), but... even taking the easy way ("unpack" video to images, stitch images, repack video):

- videos have more options to tinker with,
- separate stitching ```.pto``` file for video (different image size),

Also to consider:
- results might not what you expect (video is not horizontally corrected, vignetting, etc.),
- Windows is not my favourite platform to work in,
- it takes a very long time,
- it takes a lot of disk space,

There's this: https://github.com/walisser/vlc-filter-pipe - but it's pretty custom which means, harder to use (which I try to avoid). But that would not eliminate need to create a custom ```.pto.``` file.

Can't promise anything, but I'll think about the problem and try to implement a solution.

BTW: I think some of the commercial tools should have that.

**Comment by ultramango** [comment]
Have a look at the ```gear360video.cmd``` script, might work but it will be really slow. For running it against many files, check this: http://stackoverflow.com/questions/14237548/batch-script-run-command-on-each-file-in-directory .

**Comment by cesifoti** [comment]
Thanks! That's extremely helpful. I'll check it out and let you know how it goes. I am swamped this week with a big event, so it may take me some time to get back to you. Thanks!

**Comment by OWKenobi** [comment]
Hi,

batch video stitching should work with the latest patch from today, if you use nautilus "open with" on multiple files and select the gear360video.cmd as Program.
