### ISSUE TITLE
Crash after 10 minutes

### ISSUE THREAD

**Issue by OWKenobi** [ultramango/gear360pano#8]
hi,

photo stitching works brilliantly!

video stitching seems to work first, it creates tons of images, but finally after 10 minutes for a 6 seconds clip it crashes with this output:

.....
Stitching input images (enblend)
enblend: info: loading next image: ./tmp.DYg4ZYsa3Q/out0000.tif 1/1
enblend: info: loading next image: ./tmp.DYg4ZYsa3Q/out0001.tif 1/1
enblend: info: writing final output
Bogus input colorspace
Panorama written to ./tmp.iKrSsLZtwY/image00056.jpg, took: 20 s
Frame: ./tmp.9d4ESk3sGA/image00057.jpg
Processing input images (nona)
ContractViolation: 
Precondition violation!
Unable to open file '/home/ubuntu/Projekte/Reise/Asia3D/gear360pano-master/converter/dummy.jpg'.

ContractViolation: 
Precondition violation!
Unable to open file '/home/ubuntu/Projekte/Reise/Asia3D/gear360pano-master/converter/dummy.jpg'.

Stitching input images (enblend)
enblend: info: loading next image: ./tmp.Os5CJy2DS4/out0000.tif 1/1
enblend: info: loading next image: ./tmp.Os5CJy2DS4/out0001.tif 1/1
enblend: info: writing final output
Bogus input colorspace
Panorama written to ./tmp.iKrSsLZtwY/image00057.jpg, took: 21 s
Frame: ./tmp.9d4ESk3sGA/image00058.jpg
Processing input images (nona)
ContractViolation: 
Precondition violation!
Unable to open file '/home/ubuntu/Projekte/Reise/Asia3D/gear360pano-master/converter/dummy.jpg'.

ContractViolation: 
Precondition violation!
Unable to open file '/home/ubuntu/Projekte/Reise/Asia3D/gear360pano-master/converter/dummy.jpg'.

Stitching input images (enblend)
enblend: info: loading next image: ./tmp.sgLjoSfqp0/out0000.tif 1/1
enblend: info: loading next image: ./tmp.sgLjoSfqp0/out0001.tif 1/1
enblend: info: writing final output
Bogus input colorspace
Panorama written to ./tmp.iKrSsLZtwY/image00058.jpg, took: 20 s
Frame: ./tmp.9d4ESk3sGA/image00059.jpg
Processing input images (nona)
ContractViolation: 
Precondition violation!
Unable to open file '/home/ubuntu/Projekte/Reise/Asia3D/gear360pano-master/converter/dummy.jpg'.

ContractViolation: 
Precondition violation!
Unable to open file '/home/ubuntu/Projekte/Reise/Asia3D/gear360pano-master/converter/dummy.jpg'.

Stitching input images (enblend)
enblend: info: loading next image: ./tmp.91KxgrRl6Q/out0000.tif 1/1
enblend: info: loading next image: ./tmp.91KxgrRl6Q/out0001.tif 1/1
enblend: info: writing final output
Bogus input colorspace
Panorama written to ./tmp.iKrSsLZtwY/image00059.jpg, took: 20 s
Recoding the video...
ffmpeg version N-81995-gd790e48 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab --enable-libwavpack --enable-nvenc
  libavutil      55. 32.100 / 55. 32.100
  libavcodec     57. 61.103 / 57. 61.103
  libavformat    57. 52.100 / 57. 52.100
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 64.100 /  6. 64.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  2.100 /  2.  2.100
  libpostproc    54.  0.100 / 54.  0.100
**[image2 @ 0x3118fe0] Could find no file with path '"./tmp.iKrSsLZtwY/image%05d.jpg"' and index in the range 0-4
"./tmp.iKrSsLZtwY/image%05d.jpg": No such file or directory**
Error while running ffmpeg
Removing temporary directories...

**Comment by ultramango** [comment]
Fixed (at least works on my machine).

One thing that I've noticed is that the seam in the video is not "nice", possibly I'd need to adjust final stitching parameters (nona I think).

**Comment by OWKenobi** [comment]
awesome, I will try out today and report you back! 

One more thing about the stitching of photos: the stitch is nearly perfect, but I realize a distortion: in different shots I made, I saw that the width of the room was exaggerated, but the length of the room was pushed together. Any chance this can be finetuned with the hugin parameters? I have no idea how hugin works, too many parameters I cannot guess; I tried this myself and it was a complete disaster.

**Comment by ultramango** [comment]
I've noticed that some time ago as well when comparing Hugin panoramas with the ones coming from the phone. Don't know really which parameter is responsible for that - possibly a barrel distortion. I plan to create a new, improved Hugin template sometime in near future.

**Comment by OWKenobi** [comment]
Sounds good. Video creation works now for me, too! 

P.S. what is the recommended way of getting your updates?

**Comment by ultramango** [comment]
I'm not an expert in this github thing, I guess if you click "Watch" button in the top it should inform you about any changes to the project.
Or another possible answer: if on Linux then I think git is the easiest, just do a ```git pull``` and it should get the latest changes, otherwise use zip and overwrite files.
