### ISSUE TITLE
Exporting videos with audio, and much more (solved!)

### ISSUE THREAD

**Issue by OWKenobi** [ultramango/gear360pano#9]
Hi,

I sat down this night and improved the code a lot. These are my changes:
- Video output now includes Audio
- Nautilus "Open With" compatibility - so now you can batch stitch just by selecting many files in nautilus and click "open with"!
- Bugfixes concerning spaces in directory or file names that confused the toolchain.
- Bugfixes concerning the script living in a different directory than the current directory
- Bugfix that Video mode wouldn't delete its temporary files
- Desktop notifications when the job starts and stops or you invoke the executable without parameters
  (in open-with-mode, you don't have a terminal and don't really see anything)

the only open issue is the distortion. I figured out that the temporary .tif pictures that are produced show that one camera fills 66% of the screen while the other camera only covers 33% of the image area - this might be the cause.

Find my update here: 
[update.zip](https://github.com/ultramango/gear360pano/files/559965/update.zip)

**Comment by ultramango** [comment]
Hi,

Thanks for the fixes, I modified them a bit to fit the coding style. I also ported the changes to Windows. Let me know if it doesn't work, for any reason.

As for the TIFFs - not sure but I think (don't have any strong arguments now) that it has to be like that due to the projection used. Once I find time I will try to improve the ```.pto``` file to produce better panoramas.

**Comment by OWKenobi** [comment]
Hi Ultramango,

nice, you are back! Meanwhile I resolved an av-desync problem (see other
commit). Really hope that you can improve the .pto files - I just don't
understand hugin,

2016-11-07 0:45 GMT+01:00 ultramango <notifications@github.com>:

**Comment by ultramango** [comment]
I'll have look later this week. In the meantime I'll try to take some good photos for a better stitching template. I have also plans for recording how to do things manually.
